/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.computersupportedclasshelper.gui;

import br.com.davidbuzatto.computersupportedclasshelper.utils.Constants;
import br.com.davidbuzatto.computersupportedclasshelper.utils.DrawingConfigs;
import java.awt.Color;
import java.awt.Font;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author David
 */
public class CustomMessageAndConfirmDialog extends javax.swing.JDialog {

    private DrawingConfigs dConfig;
    private KeyEventDispatcher keyEventDispatcher;
    private int returnData;
    
    /**
     * Creates new form CustomMessageAndConfirmDialog
     */
    private CustomMessageAndConfirmDialog( java.awt.Window parent, boolean showCancelOption ) {
        
        super( parent, ModalityType.APPLICATION_MODAL );
        initComponents();
        
        setBackground( new Color( 0, 0, 0, 0 ) );
        dConfig = DrawingConfigs.getInstance();
        dConfig.setProcessEventsMainWindow( false );
        getRootPane().setDefaultButton( btnOK );
        containerPanel.setForMessageAndInputDialogs( true );
        
        if ( !showCancelOption ) {
            btnCancel.setVisible( false );
        }
        
        keyEventDispatcher = new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent( KeyEvent e ) {
                if ( e.getKeyCode() == KeyEvent.VK_ESCAPE ) {
                    returnData = JOptionPane.NO_OPTION;
                    dispose();
                }
                return false;
            }
        };
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher( keyEventDispatcher );
        
        addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosed( WindowEvent e ) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher( keyEventDispatcher );
            }
        });
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel();
        containerBtns = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        containerBtns.setOpaque(false);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/accept.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        containerBtns.add(btnOK);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/delete.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        containerBtns.add(btnCancel);

        lblTitle.setFont(new Font( "Dialog", Font.BOLD, 12 )
        );
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("title");

        lblMessage.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lblMessage.setForeground(new java.awt.Color(204, 204, 204));
        lblMessage.setText("message");

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerBtns, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(242, 142));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        returnData = JOptionPane.YES_OPTION;
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        returnData = JOptionPane.NO_OPTION;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    @Override
    public void dispose() {
        super.dispose();
        dConfig.setProcessEventsMainWindow( true );
    }
    
    public static void showMessageDialog(
            java.awt.Window owner, String message, String title, int type ) {
        
        CustomMessageAndConfirmDialog dialog = new CustomMessageAndConfirmDialog( 
                owner, false );
        dialog.lblTitle.setText( title );
        dialog.lblMessage.setText( message );
        setColorTheme( dialog, type );
        dialog.setVisible( true );
        
    }
    
    public static int showConfirmDialog(
            java.awt.Window owner, String message, String title ) {
        
        CustomMessageAndConfirmDialog dialog = new CustomMessageAndConfirmDialog( 
                owner, false );
        
        dialog.lblTitle.setText( title );
        dialog.lblMessage.setText( message );
        dialog.btnCancel.setVisible( true );
        setColorTheme( dialog, JOptionPane.QUESTION_MESSAGE );
        dialog.setVisible( true );
        
        return dialog.returnData;
        
    }
    
    private static void setColorTheme( CustomMessageAndConfirmDialog dialog, int type ) {
        
        switch ( type ) {
            case JOptionPane.INFORMATION_MESSAGE:
                dialog.containerPanel.setBackgroundColor( Constants.COMPONENT_BACKGROUND_COLOR_INFORMATION );
                dialog.containerPanel.setStrokeColor( Constants.COMPONENT_STROKE_COLOR_INFORMATION );
                dialog.lblIcon.setIcon( UIManager.getIcon( "OptionPane.informationIcon" ) );
                break;
            case JOptionPane.QUESTION_MESSAGE:
                dialog.containerPanel.setBackgroundColor( Constants.COMPONENT_BACKGROUND_COLOR_QUESTION );
                dialog.containerPanel.setStrokeColor( Constants.COMPONENT_STROKE_COLOR_QUESTION );
                dialog.lblIcon.setIcon( UIManager.getIcon( "OptionPane.questionIcon" ) );
                break;
            case JOptionPane.WARNING_MESSAGE:
                dialog.containerPanel.setBackgroundColor( Constants.COMPONENT_BACKGROUND_COLOR_WARNING );
                dialog.containerPanel.setStrokeColor( Constants.COMPONENT_STROKE_COLOR_WARNING );
                dialog.lblIcon.setIcon( UIManager.getIcon( "OptionPane.warningIcon" ) );
                break;
            case JOptionPane.ERROR_MESSAGE:
                dialog.containerPanel.setBackgroundColor( Constants.COMPONENT_BACKGROUND_COLOR_ERROR );
                dialog.containerPanel.setStrokeColor( Constants.COMPONENT_STROKE_COLOR_ERROR );
                dialog.lblIcon.setIcon( UIManager.getIcon( "OptionPane.errorIcon" ) );
                break;
            default: // PLAIN
                dialog.containerPanel.setBackgroundColor( Constants.COMPONENT_BACKGROUND_COLOR_INFORMATION );
                dialog.containerPanel.setStrokeColor( Constants.COMPONENT_STROKE_COLOR_INFORMATION );
                break;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel containerBtns;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel containerPanel;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
