/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.computersupportedclasshelper.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author David
 */
public class PalettePanel extends javax.swing.JPanel {

    /**
     * Creates new form PalettePanel
     */
    public PalettePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plbl = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        pc1 = new javax.swing.JPanel();
        cps1 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf1 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc2 = new javax.swing.JPanel();
        cps2 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf2 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc3 = new javax.swing.JPanel();
        cps3 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf3 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc4 = new javax.swing.JPanel();
        cps4 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf4 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc5 = new javax.swing.JPanel();
        cps5 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf5 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc6 = new javax.swing.JPanel();
        cps6 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf6 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc7 = new javax.swing.JPanel();
        cps7 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf7 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pc8 = new javax.swing.JPanel();
        cps8 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        cpf8 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel();
        pb = new javax.swing.JPanel();
        btn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        plbl.setOpaque(false);

        lbl.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lbl.setForeground(new java.awt.Color(188, 188, 188));
        lbl.setText("lbl");
        plbl.add(lbl);

        add(plbl);

        pc1.setOpaque(false);

        javax.swing.GroupLayout cps1Layout = new javax.swing.GroupLayout(cps1);
        cps1.setLayout(cps1Layout);
        cps1Layout.setHorizontalGroup(
            cps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps1Layout.setVerticalGroup(
            cps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc1.add(cps1);

        javax.swing.GroupLayout cpf1Layout = new javax.swing.GroupLayout(cpf1);
        cpf1.setLayout(cpf1Layout);
        cpf1Layout.setHorizontalGroup(
            cpf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf1Layout.setVerticalGroup(
            cpf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc1.add(cpf1);

        add(pc1);

        pc2.setOpaque(false);

        javax.swing.GroupLayout cps2Layout = new javax.swing.GroupLayout(cps2);
        cps2.setLayout(cps2Layout);
        cps2Layout.setHorizontalGroup(
            cps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps2Layout.setVerticalGroup(
            cps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc2.add(cps2);

        javax.swing.GroupLayout cpf2Layout = new javax.swing.GroupLayout(cpf2);
        cpf2.setLayout(cpf2Layout);
        cpf2Layout.setHorizontalGroup(
            cpf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf2Layout.setVerticalGroup(
            cpf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc2.add(cpf2);

        add(pc2);

        pc3.setOpaque(false);

        javax.swing.GroupLayout cps3Layout = new javax.swing.GroupLayout(cps3);
        cps3.setLayout(cps3Layout);
        cps3Layout.setHorizontalGroup(
            cps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps3Layout.setVerticalGroup(
            cps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc3.add(cps3);

        javax.swing.GroupLayout cpf3Layout = new javax.swing.GroupLayout(cpf3);
        cpf3.setLayout(cpf3Layout);
        cpf3Layout.setHorizontalGroup(
            cpf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf3Layout.setVerticalGroup(
            cpf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc3.add(cpf3);

        add(pc3);

        pc4.setOpaque(false);

        javax.swing.GroupLayout cps4Layout = new javax.swing.GroupLayout(cps4);
        cps4.setLayout(cps4Layout);
        cps4Layout.setHorizontalGroup(
            cps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps4Layout.setVerticalGroup(
            cps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc4.add(cps4);

        javax.swing.GroupLayout cpf4Layout = new javax.swing.GroupLayout(cpf4);
        cpf4.setLayout(cpf4Layout);
        cpf4Layout.setHorizontalGroup(
            cpf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf4Layout.setVerticalGroup(
            cpf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc4.add(cpf4);

        add(pc4);

        pc5.setOpaque(false);

        javax.swing.GroupLayout cps5Layout = new javax.swing.GroupLayout(cps5);
        cps5.setLayout(cps5Layout);
        cps5Layout.setHorizontalGroup(
            cps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps5Layout.setVerticalGroup(
            cps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc5.add(cps5);

        javax.swing.GroupLayout cpf5Layout = new javax.swing.GroupLayout(cpf5);
        cpf5.setLayout(cpf5Layout);
        cpf5Layout.setHorizontalGroup(
            cpf5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf5Layout.setVerticalGroup(
            cpf5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc5.add(cpf5);

        add(pc5);

        pc6.setOpaque(false);

        javax.swing.GroupLayout cps6Layout = new javax.swing.GroupLayout(cps6);
        cps6.setLayout(cps6Layout);
        cps6Layout.setHorizontalGroup(
            cps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps6Layout.setVerticalGroup(
            cps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc6.add(cps6);

        javax.swing.GroupLayout cpf6Layout = new javax.swing.GroupLayout(cpf6);
        cpf6.setLayout(cpf6Layout);
        cpf6Layout.setHorizontalGroup(
            cpf6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf6Layout.setVerticalGroup(
            cpf6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc6.add(cpf6);

        add(pc6);

        pc7.setOpaque(false);

        javax.swing.GroupLayout cps7Layout = new javax.swing.GroupLayout(cps7);
        cps7.setLayout(cps7Layout);
        cps7Layout.setHorizontalGroup(
            cps7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps7Layout.setVerticalGroup(
            cps7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc7.add(cps7);

        javax.swing.GroupLayout cpf7Layout = new javax.swing.GroupLayout(cpf7);
        cpf7.setLayout(cpf7Layout);
        cpf7Layout.setHorizontalGroup(
            cpf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf7Layout.setVerticalGroup(
            cpf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc7.add(cpf7);

        add(pc7);

        pc8.setOpaque(false);

        javax.swing.GroupLayout cps8Layout = new javax.swing.GroupLayout(cps8);
        cps8.setLayout(cps8Layout);
        cps8Layout.setHorizontalGroup(
            cps8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cps8Layout.setVerticalGroup(
            cps8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc8.add(cps8);

        javax.swing.GroupLayout cpf8Layout = new javax.swing.GroupLayout(cpf8);
        cpf8.setLayout(cpf8Layout);
        cpf8Layout.setHorizontalGroup(
            cpf8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cpf8Layout.setVerticalGroup(
            cpf8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pc8.add(cpf8);

        add(pc8);

        pb.setOpaque(false);

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/accept.png"))); // NOI18N
        pb.add(btn);

        add(pb);
    }// </editor-fold>//GEN-END:initComponents

    public void addActionListener( ActionListener al ) {
        btn.addActionListener( al );
    }
    
    public void setPaletteName( String name ) {
        lbl.setText( name );
    }
    
    public String getPaletteName() {
        return lbl.getText();
    }
    
    public void setStrokeColor01( Color color ) {
        cps1.setColor( color );
    }
    
    public Color getStrokeColor01() {
        return cps1.getColor();
    }
    
    public void setStrokeColor02( Color color ) {
        cps2.setColor( color );
    }
    
    public Color getStrokeColor02() {
        return cps2.getColor();
    }
    
    public void setStrokeColor03( Color color ) {
        cps3.setColor( color );
    }
    
    public Color getStrokeColor03() {
        return cps3.getColor();
    }
    
    public void setStrokeColor04( Color color ) {
        cps4.setColor( color );
    }
    
    public Color getStrokeColor04() {
        return cps4.getColor();
    }
    
    public void setStrokeColor05( Color color ) {
        cps5.setColor( color );
    }
    
    public Color getStrokeColor05() {
        return cps5.getColor();
    }
    
    public void setStrokeColor06( Color color ) {
        cps6.setColor( color );
    }
    
    public Color getStrokeColor06() {
        return cps6.getColor();
    }
    
    public void setStrokeColor07( Color color ) {
        cps7.setColor( color );
    }
    
    public Color getStrokeColor07() {
        return cps7.getColor();
    }
    
    public void setStrokeColor08( Color color ) {
        cps8.setColor( color );
    }
    
    public Color getStrokeColor08() {
        return cps8.getColor();
    }
    
    public void setFillColor01( Color color ) {
        cpf1.setColor( color );
    }
    
    public Color getFillColor01() {
        return cpf1.getColor();
    }
    
    public void setFillColor02( Color color ) {
        cpf2.setColor( color );
    }
    
    public Color getFillColor02() {
        return cpf2.getColor();
    }
    
    public void setFillColor03( Color color ) {
        cpf3.setColor( color );
    }
    
    public Color getFillColor03() {
        return cpf3.getColor();
    }
    
    public void setFillColor04( Color color ) {
        cpf4.setColor( color );
    }
    
    public Color getFillColor04() {
        return cpf4.getColor();
    }
    
    public void setFillColor05( Color color ) {
        cpf5.setColor( color );
    }
    
    public Color getFillColor05() {
        return cpf5.getColor();
    }
    
    public void setFillColor06( Color color ) {
        cpf6.setColor( color );
    }
    
    public Color getFillColor06() {
        return cpf6.getColor();
    }
    
    public void setFillColor07( Color color ) {
        cpf7.setColor( color );
    }
    
    public Color getFillColor07() {
        return cpf7.getColor();
    }
    
    public void setFillColor08( Color color ) {
        cpf8.setColor( color );
    }
    
    public Color getFillColor08() {
        return cpf8.getColor();
    }
    
    public Map<String, Color> getColors() {
        
        Map<String, Color> colors = new LinkedHashMap<>();
        
        colors.put( "sc1", getStrokeColor01() );
        colors.put( "sc2", getStrokeColor02() );
        colors.put( "sc3", getStrokeColor03() );
        colors.put( "sc4", getStrokeColor04() );
        colors.put( "sc5", getStrokeColor05() );
        colors.put( "sc6", getStrokeColor06() );
        colors.put( "sc7", getStrokeColor07() );
        colors.put( "sc8", getStrokeColor08() );
        
        colors.put( "fc1", getFillColor01() );
        colors.put( "fc2", getFillColor02() );
        colors.put( "fc3", getFillColor03() );
        colors.put( "fc4", getFillColor04() );
        colors.put( "fc5", getFillColor05() );
        colors.put( "fc6", getFillColor06() );
        colors.put( "fc7", getFillColor07() );
        colors.put( "fc8", getFillColor08() );
        
        return colors;
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf1;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf2;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf3;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf4;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf5;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf6;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf7;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cpf8;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps1;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps2;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps3;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps4;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps5;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps6;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps7;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ColorPanel cps8;
    private javax.swing.JLabel lbl;
    private javax.swing.JPanel pb;
    private javax.swing.JPanel pc1;
    private javax.swing.JPanel pc2;
    private javax.swing.JPanel pc3;
    private javax.swing.JPanel pc4;
    private javax.swing.JPanel pc5;
    private javax.swing.JPanel pc6;
    private javax.swing.JPanel pc7;
    private javax.swing.JPanel pc8;
    private javax.swing.JPanel plbl;
    // End of variables declaration//GEN-END:variables
}
