/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.computersupportedclasshelper.gui;

import br.com.davidbuzatto.computersupportedclasshelper.utils.DrawingConfigs;
import br.com.davidbuzatto.computersupportedclasshelper.utils.FontAlignmentEnum;
import br.com.davidbuzatto.computersupportedclasshelper.utils.FontTypeEnum;
import java.awt.Color;
import java.awt.Font;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JToggleButton;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class ToolConfigDialogText extends javax.swing.JDialog {

    private DrawingConfigs dConfig;
    private KeyEventDispatcher keyEventDispatcher;
    private JToggleButton[] tBtns;
    private Color tBtnsSelectedColor;
    
    /**
     * Creates new form ToolConfigDialogStrokeWidth
     */
    public ToolConfigDialogText( java.awt.Frame parent, boolean modal ) {
        
        super( parent, modal );
        initComponents();
        setBackground( new Color( 0, 0, 0, 0 ) );
        
        tBtns = new JToggleButton[]{ 
            tBtnBold,
            tBtnItalic,
            tBtnLeft,
            tBtnCenter,
            tBtnRight
        };
        
        tBtnsSelectedColor = Color.GRAY.brighter();
        
        dConfig = DrawingConfigs.getInstance();
        dConfig.setProcessEventsMainWindow( false );
        
        switch ( dConfig.getFontType() ) {
            case DIALOG:
                radioDialog.setSelected( true );
                break;
            case SANS_SERIF:
                radioSansSerif.setSelected( true );
                break;
            case SERIF:
                radioSerif.setSelected( true );
                break;
            case MONOSPACED:
                radioMonospaced.setSelected( true );
                break;
        }
        
        spinSize.setValue( dConfig.getFontSize() );
        
        tBtnBold.setSelected( dConfig.isFontIsBold() );
        tBtnItalic.setSelected( dConfig.isFontIsItalic());
        
        switch ( dConfig.getFontAlignment() ) {
            case LEFT:
                tBtnLeft.setSelected( true );
                break;
            case CENTER:
                tBtnCenter.setSelected( true );
                break;
            case RIGHT:
                tBtnRight.setSelected( true );
                break;
        }
        
        setToggleButtonsColor();
        getRootPane().setDefaultButton( btnOK );
        
        keyEventDispatcher = new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent( KeyEvent e ) {
                if ( e.getKeyCode() == KeyEvent.VK_ESCAPE ) {
                    dispose();
                }
                return false;
            }
        };
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher( keyEventDispatcher );
        
        addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosed( WindowEvent e ) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher( keyEventDispatcher );
            }
        });
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroupFontAlign = new javax.swing.ButtonGroup();
        containerPanel = new br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel();
        lblFont = new javax.swing.JLabel();
        customDialogContainerPanel2 = new br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel();
        lblSize = new javax.swing.JLabel();
        spinSize = new javax.swing.JSpinner();
        tBtnBold = new javax.swing.JToggleButton();
        tBtnItalic = new javax.swing.JToggleButton();
        tBtnLeft = new javax.swing.JToggleButton();
        tBtnCenter = new javax.swing.JToggleButton();
        tBtnRight = new javax.swing.JToggleButton();
        customDialogContainerPanel1 = new br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel();
        radioDialog = new javax.swing.JRadioButton();
        radioSansSerif = new javax.swing.JRadioButton();
        radioSerif = new javax.swing.JRadioButton();
        radioMonospaced = new javax.swing.JRadioButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblFont.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lblFont.setText("Font:");

        lblSize.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lblSize.setForeground(new java.awt.Color(204, 204, 204));
        lblSize.setText("Size:");

        spinSize.setModel(new javax.swing.SpinnerNumberModel(12, 4, 200, 1));
        spinSize.setEditor(new javax.swing.JSpinner.NumberEditor(spinSize, ""));

        tBtnBold.setBackground(new java.awt.Color(255, 255, 255));
        tBtnBold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/text_bold.png"))); // NOI18N
        tBtnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnBoldActionPerformed(evt);
            }
        });

        tBtnItalic.setBackground(new java.awt.Color(255, 255, 255));
        tBtnItalic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/text_italic.png"))); // NOI18N
        tBtnItalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnItalicActionPerformed(evt);
            }
        });

        tBtnLeft.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupFontAlign.add(tBtnLeft);
        tBtnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/text_align_left.png"))); // NOI18N
        tBtnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnLeftActionPerformed(evt);
            }
        });

        tBtnCenter.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupFontAlign.add(tBtnCenter);
        tBtnCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/text_align_center.png"))); // NOI18N
        tBtnCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnCenterActionPerformed(evt);
            }
        });

        tBtnRight.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupFontAlign.add(tBtnRight);
        tBtnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/text_align_right.png"))); // NOI18N
        tBtnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customDialogContainerPanel2Layout = new javax.swing.GroupLayout(customDialogContainerPanel2);
        customDialogContainerPanel2.setLayout(customDialogContainerPanel2Layout);
        customDialogContainerPanel2Layout.setHorizontalGroup(
            customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customDialogContainerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customDialogContainerPanel2Layout.createSequentialGroup()
                        .addComponent(lblSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customDialogContainerPanel2Layout.createSequentialGroup()
                        .addComponent(tBtnBold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtnItalic))
                    .addGroup(customDialogContainerPanel2Layout.createSequentialGroup()
                        .addComponent(tBtnLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtnCenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBtnRight)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customDialogContainerPanel2Layout.setVerticalGroup(
            customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customDialogContainerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize)
                    .addComponent(spinSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tBtnBold)
                    .addComponent(tBtnItalic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customDialogContainerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tBtnLeft)
                    .addComponent(tBtnCenter)
                    .addComponent(tBtnRight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup.add(radioDialog);
        radioDialog.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        radioDialog.setForeground(new java.awt.Color(204, 204, 204));
        radioDialog.setSelected(true);
        radioDialog.setText("Dialog");

        buttonGroup.add(radioSansSerif);
        radioSansSerif.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        radioSansSerif.setForeground(new java.awt.Color(204, 204, 204));
        radioSansSerif.setText("SansSerif");

        buttonGroup.add(radioSerif);
        radioSerif.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        radioSerif.setForeground(new java.awt.Color(204, 204, 204));
        radioSerif.setText("Serif");

        buttonGroup.add(radioMonospaced);
        radioMonospaced.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        radioMonospaced.setForeground(new java.awt.Color(204, 204, 204));
        radioMonospaced.setText("Monospaced");

        javax.swing.GroupLayout customDialogContainerPanel1Layout = new javax.swing.GroupLayout(customDialogContainerPanel1);
        customDialogContainerPanel1.setLayout(customDialogContainerPanel1Layout);
        customDialogContainerPanel1Layout.setHorizontalGroup(
            customDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customDialogContainerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDialog)
                    .addComponent(radioSansSerif)
                    .addComponent(radioSerif)
                    .addComponent(radioMonospaced))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customDialogContainerPanel1Layout.setVerticalGroup(
            customDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customDialogContainerPanel1Layout.createSequentialGroup()
                .addComponent(radioDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSansSerif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSerif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMonospaced)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/accept.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/delete.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFont)
                        .addGroup(containerPanelLayout.createSequentialGroup()
                            .addComponent(customDialogContainerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(customDialogContainerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblFont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customDialogContainerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customDialogContainerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        if ( radioDialog.isSelected() ) {
            dConfig.setFontType( FontTypeEnum.DIALOG );
        } else if ( radioSansSerif.isSelected() ) {
            dConfig.setFontType( FontTypeEnum.SANS_SERIF );
        } else if ( radioSerif.isSelected() ) {
            dConfig.setFontType( FontTypeEnum.SERIF );
        } else {
            dConfig.setFontType( FontTypeEnum.MONOSPACED );
        }
        
        dConfig.setFontSize( (int) Double.parseDouble( String.valueOf( spinSize.getValue() ) ) );
        
        dConfig.setFontIsBold( tBtnBold.isSelected() );
        dConfig.setFontIsItalic( tBtnItalic.isSelected() );
        
        if ( tBtnLeft.isSelected() ) {
            dConfig.setFontAlignment( FontAlignmentEnum.LEFT );
        } else if ( tBtnCenter.isSelected() ) {
            dConfig.setFontAlignment( FontAlignmentEnum.CENTER );
        } else {
            dConfig.setFontAlignment( FontAlignmentEnum.RIGHT );
        }
        
        dispose();
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tBtnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnBoldActionPerformed
        setToggleButtonsColor();
    }//GEN-LAST:event_tBtnBoldActionPerformed

    private void tBtnItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnItalicActionPerformed
        setToggleButtonsColor();
    }//GEN-LAST:event_tBtnItalicActionPerformed

    private void tBtnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnLeftActionPerformed
        setToggleButtonsColor();
    }//GEN-LAST:event_tBtnLeftActionPerformed

    private void tBtnCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnCenterActionPerformed
        setToggleButtonsColor();
    }//GEN-LAST:event_tBtnCenterActionPerformed

    private void tBtnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnRightActionPerformed
        setToggleButtonsColor();
    }//GEN-LAST:event_tBtnRightActionPerformed

    @Override
    public void dispose() {
        super.dispose();
        dConfig.setProcessEventsMainWindow( true );
    }

    private void setToggleButtonsColor() {
        
        for ( JToggleButton t : tBtns ) {
            if ( t.isSelected() ) {
                t.setBackground( tBtnsSelectedColor );
            } else {
                t.setBackground( Color.WHITE );
            }
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroupFontAlign;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel containerPanel;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel customDialogContainerPanel1;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel customDialogContainerPanel2;
    private javax.swing.JLabel lblFont;
    private javax.swing.JLabel lblSize;
    private javax.swing.JRadioButton radioDialog;
    private javax.swing.JRadioButton radioMonospaced;
    private javax.swing.JRadioButton radioSansSerif;
    private javax.swing.JRadioButton radioSerif;
    private javax.swing.JSpinner spinSize;
    private javax.swing.JToggleButton tBtnBold;
    private javax.swing.JToggleButton tBtnCenter;
    private javax.swing.JToggleButton tBtnItalic;
    private javax.swing.JToggleButton tBtnLeft;
    private javax.swing.JToggleButton tBtnRight;
    // End of variables declaration//GEN-END:variables
}
