/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.computersupportedclasshelper.gui;

import br.com.davidbuzatto.computersupportedclasshelper.utils.DrawingConfigs;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class ToolConfigDialogStrokeWidthSideQuantity extends javax.swing.JDialog {

    private DrawingConfigs dConfig;
    
    /**
     * Creates new form ToolConfigDialog
     */
    public ToolConfigDialogStrokeWidthSideQuantity( java.awt.Frame parent, boolean modal ) {
        
        super( parent, modal );
        initComponents();
        setBackground( new Color( 0, 0, 0, 0 ) );
        
        dConfig = DrawingConfigs.getInstance();
        dConfig.setProcessEventsMainWindow( false );
        
        fieldStrokeWidth.setText( String.valueOf( dConfig.getStrokeWidth() ) );
        fieldSideQuantity.setText( String.valueOf( dConfig.getSideQuantity() ) );
        getRootPane().setDefaultButton( btnOK );
        
        fieldStrokeWidth.addKeyListener( new KeyAdapter() {
            @Override
            public void keyReleased( KeyEvent e ) {
                if ( e.getKeyCode() == KeyEvent.VK_ESCAPE ) {
                    dispose();
                }
            }
        });
        
        fieldSideQuantity.addKeyListener( new KeyAdapter() {
            @Override
            public void keyReleased( KeyEvent e ) {
                if ( e.getKeyCode() == KeyEvent.VK_ESCAPE ) {
                    dispose();
                }
            }
        });
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolConfigDialogContainerPanel1 = new br.com.davidbuzatto.computersupportedclasshelper.gui.ToolConfigDialogContainerPanel();
        lblStrokeWidth = new javax.swing.JLabel();
        lblSideQuantity = new javax.swing.JLabel();
        fieldStrokeWidth = new javax.swing.JTextField();
        fieldSideQuantity = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblStrokeWidth.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lblStrokeWidth.setForeground(new java.awt.Color(204, 204, 204));
        lblStrokeWidth.setText("Stroke Width:");

        lblSideQuantity.setFont(new Font( "Dialog", Font.BOLD, 12 ));
        lblSideQuantity.setForeground(new java.awt.Color(204, 204, 204));
        lblSideQuantity.setText("Side Quantity:");

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/accept.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/delete.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolConfigDialogContainerPanel1Layout = new javax.swing.GroupLayout(toolConfigDialogContainerPanel1);
        toolConfigDialogContainerPanel1.setLayout(toolConfigDialogContainerPanel1Layout);
        toolConfigDialogContainerPanel1Layout.setHorizontalGroup(
            toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolConfigDialogContainerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStrokeWidth)
                    .addComponent(lblSideQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldStrokeWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSideQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toolConfigDialogContainerPanel1Layout.setVerticalGroup(
            toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolConfigDialogContainerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrokeWidth)
                    .addComponent(fieldStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toolConfigDialogContainerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSideQuantity)
                    .addComponent(fieldSideQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolConfigDialogContainerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolConfigDialogContainerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        try {
            
            DrawingConfigs dc = DrawingConfigs.getInstance();
            double newStrokeWith = Double.parseDouble( fieldStrokeWidth.getText() );
            int newSideQuantity = Integer.parseInt( fieldSideQuantity.getText() );
            
            if ( newStrokeWith <= 0 ) {
                JOptionPane.showMessageDialog( this.getOwner(), 
                        "The Stroke Width must be greater than zero!", 
                        "ERROR", JOptionPane.ERROR_MESSAGE );
            } else if ( newSideQuantity <= 2 ) {
                JOptionPane.showMessageDialog( this.getOwner(), 
                        "The Side Quantity must be greater than two!", 
                        "ERROR", JOptionPane.ERROR_MESSAGE );
            } else {
                dc.setStrokeWidth( newStrokeWith );
                dc.setSideQuantity( newSideQuantity );
                dispose();
            }
            
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( this.getOwner(), 
                    "The Stroke Width and the Side Quantity must be a number!", 
                    "ERROR", JOptionPane.ERROR_MESSAGE );
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    @Override
    public void dispose() {
        super.dispose();
        dConfig.setProcessEventsMainWindow( true );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger(ToolConfigDialogStrokeWidthSideQuantity.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger(ToolConfigDialogStrokeWidthSideQuantity.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger(ToolConfigDialogStrokeWidthSideQuantity.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger(ToolConfigDialogStrokeWidthSideQuantity.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ToolConfigDialogStrokeWidthSideQuantity dialog = new ToolConfigDialogStrokeWidthSideQuantity( new javax.swing.JFrame(), true );
                dialog.addWindowListener( new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e ) {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField fieldSideQuantity;
    private javax.swing.JTextField fieldStrokeWidth;
    private javax.swing.JLabel lblSideQuantity;
    private javax.swing.JLabel lblStrokeWidth;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.ToolConfigDialogContainerPanel toolConfigDialogContainerPanel1;
    // End of variables declaration//GEN-END:variables
}
