/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.computersupportedclasshelper.gui;

import br.com.davidbuzatto.computersupportedclasshelper.utils.DrawingConfigs;
import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class ToolConfigDialogPalette extends javax.swing.JDialog {

    private DrawingConfigs dConfig;
    private KeyEventDispatcher keyEventDispatcher;
    
    /**
     * Creates new form ToolConfigDialogPalette
     */
    public ToolConfigDialogPalette( java.awt.Frame parent, boolean modal ) {
        
        super( parent, modal );
        initComponents();
        setBackground( new Color( 0, 0, 0, 0 ) );
        
        final MainWindow mw = (MainWindow) parent;
        
        dConfig = DrawingConfigs.getInstance();
        dConfig.setProcessEventsMainWindow( false );
        
        keyEventDispatcher = new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent( KeyEvent e ) {
                if ( e.getKeyCode() == KeyEvent.VK_ESCAPE ) {
                    dispose();
                }
                return false;
            }
        };
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher( keyEventDispatcher );
        
        addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosed( WindowEvent e ) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher( keyEventDispatcher );
            }
        });
        
        palettePanelDefault.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelDefault.getColors() );
                dispose();
            }
        });
        
        palettePanelEarth.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelEarth.getColors() );
                dispose();
            }
        });
        
        palettePanelWater.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelWater.getColors() );
                dispose();
            }
        });
        
        palettePanelFire.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelFire.getColors() );
                dispose();
            }
        });
        
        palettePanelNature.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelNature.getColors() );
                dispose();
            }
        });
        
        palettePanelNocturne.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                mw.moveColors( palettePanelNocturne.getColors() );
                dispose();
            }
        });
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel();
        palettePanelDefault = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        palettePanelEarth = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        palettePanelWater = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        palettePanelFire = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        palettePanelNature = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        palettePanelNocturne = new br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel();
        pCancel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        palettePanelDefault.setFillColor01(null);
        palettePanelDefault.setFillColor02(null);
        palettePanelDefault.setFillColor03(null);
        palettePanelDefault.setFillColor04(null);
        palettePanelDefault.setFillColor05(null);
        palettePanelDefault.setFillColor06(null);
        palettePanelDefault.setFillColor07(null);
        palettePanelDefault.setFillColor08(null);
        palettePanelDefault.setPaletteName("Default");
        palettePanelDefault.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelDefault.setStrokeColor03(new java.awt.Color(0, 153, 255));
        palettePanelDefault.setStrokeColor04(new java.awt.Color(0, 204, 51));
        palettePanelDefault.setStrokeColor05(new java.awt.Color(255, 102, 0));
        palettePanelDefault.setStrokeColor06(new java.awt.Color(255, 0, 51));
        palettePanelDefault.setStrokeColor07(new java.awt.Color(255, 0, 204));
        palettePanelDefault.setStrokeColor08(new java.awt.Color(102, 0, 204));

        palettePanelEarth.setFillColor01(null);
        palettePanelEarth.setFillColor02(null);
        palettePanelEarth.setFillColor03(null);
        palettePanelEarth.setFillColor04(null);
        palettePanelEarth.setFillColor05(null);
        palettePanelEarth.setFillColor06(null);
        palettePanelEarth.setFillColor07(null);
        palettePanelEarth.setFillColor08(null);
        palettePanelEarth.setPaletteName("Earth");
        palettePanelEarth.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelEarth.setStrokeColor03(new java.awt.Color(165, 48, 16));
        palettePanelEarth.setStrokeColor04(new java.awt.Color(222, 126, 24));
        palettePanelEarth.setStrokeColor05(new java.awt.Color(159, 131, 81));
        palettePanelEarth.setStrokeColor06(new java.awt.Color(114, 134, 83));
        palettePanelEarth.setStrokeColor07(new java.awt.Color(176, 170, 76));
        palettePanelEarth.setStrokeColor08(new java.awt.Color(106, 172, 145));

        palettePanelWater.setFillColor01(null);
        palettePanelWater.setFillColor02(null);
        palettePanelWater.setFillColor03(null);
        palettePanelWater.setFillColor04(null);
        palettePanelWater.setFillColor05(null);
        palettePanelWater.setFillColor06(null);
        palettePanelWater.setFillColor07(null);
        palettePanelWater.setFillColor08(null);
        palettePanelWater.setPaletteName("Water");
        palettePanelWater.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelWater.setStrokeColor03(new java.awt.Color(28, 173, 228));
        palettePanelWater.setStrokeColor04(new java.awt.Color(38, 131, 198));
        palettePanelWater.setStrokeColor05(new java.awt.Color(39, 206, 215));
        palettePanelWater.setStrokeColor06(new java.awt.Color(66, 186, 151));
        palettePanelWater.setStrokeColor07(new java.awt.Color(62, 136, 83));
        palettePanelWater.setStrokeColor08(new java.awt.Color(98, 163, 159));

        palettePanelFire.setFillColor01(null);
        palettePanelFire.setFillColor02(null);
        palettePanelFire.setFillColor03(null);
        palettePanelFire.setFillColor04(null);
        palettePanelFire.setFillColor05(null);
        palettePanelFire.setFillColor06(null);
        palettePanelFire.setFillColor07(null);
        palettePanelFire.setFillColor08(null);
        palettePanelFire.setPaletteName("Fire");
        palettePanelFire.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelFire.setStrokeColor03(new java.awt.Color(102, 0, 0));
        palettePanelFire.setStrokeColor04(new java.awt.Color(204, 0, 0));
        palettePanelFire.setStrokeColor05(new java.awt.Color(255, 0, 0));
        palettePanelFire.setStrokeColor06(new java.awt.Color(255, 51, 0));
        palettePanelFire.setStrokeColor07(new java.awt.Color(255, 153, 0));
        palettePanelFire.setStrokeColor08(new java.awt.Color(255, 255, 51));

        palettePanelNature.setFillColor01(null);
        palettePanelNature.setFillColor02(null);
        palettePanelNature.setFillColor03(null);
        palettePanelNature.setFillColor04(null);
        palettePanelNature.setFillColor05(null);
        palettePanelNature.setFillColor06(null);
        palettePanelNature.setFillColor07(null);
        palettePanelNature.setFillColor08(null);
        palettePanelNature.setPaletteName("Nature");
        palettePanelNature.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelNature.setStrokeColor03(new java.awt.Color(0, 102, 0));
        palettePanelNature.setStrokeColor04(new java.awt.Color(0, 153, 51));
        palettePanelNature.setStrokeColor05(new java.awt.Color(0, 204, 51));
        palettePanelNature.setStrokeColor06(new java.awt.Color(51, 255, 51));
        palettePanelNature.setStrokeColor07(new java.awt.Color(102, 255, 102));
        palettePanelNature.setStrokeColor08(new java.awt.Color(153, 255, 153));

        palettePanelNocturne.setFillColor01(null);
        palettePanelNocturne.setFillColor02(null);
        palettePanelNocturne.setFillColor03(null);
        palettePanelNocturne.setFillColor04(null);
        palettePanelNocturne.setFillColor05(null);
        palettePanelNocturne.setFillColor06(null);
        palettePanelNocturne.setFillColor07(null);
        palettePanelNocturne.setFillColor08(null);
        palettePanelNocturne.setPaletteName("Nocturne");
        palettePanelNocturne.setStrokeColor02(new java.awt.Color(255, 255, 255));
        palettePanelNocturne.setStrokeColor03(new java.awt.Color(0, 51, 204));
        palettePanelNocturne.setStrokeColor04(new java.awt.Color(0, 102, 255));
        palettePanelNocturne.setStrokeColor05(new java.awt.Color(102, 102, 255));
        palettePanelNocturne.setStrokeColor06(new java.awt.Color(153, 51, 255));
        palettePanelNocturne.setStrokeColor07(new java.awt.Color(204, 0, 204));
        palettePanelNocturne.setStrokeColor08(new java.awt.Color(102, 0, 51));

        pCancel.setOpaque(false);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/computersupportedclasshelper/gui/icons/delete.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pCancel.add(btnCancel);

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(palettePanelDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palettePanelEarth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palettePanelWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palettePanelFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palettePanelNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palettePanelNocturne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palettePanelNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palettePanelWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palettePanelDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palettePanelEarth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palettePanelFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palettePanelNocturne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    @Override
    public void dispose() {
        super.dispose();
        dConfig.setProcessEventsMainWindow( true );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.CustomDialogContainerPanel containerPanel;
    private javax.swing.JPanel pCancel;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelDefault;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelEarth;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelFire;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelNature;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelNocturne;
    private br.com.davidbuzatto.computersupportedclasshelper.gui.PalettePanel palettePanelWater;
    // End of variables declaration//GEN-END:variables
}
